### PR TITLE
[Fix #287] Eviction warning summary shows only binary incompatible

### LINKED ISSUE #287: Inconsistent log level of eviction warning summary
## Summary

Eviction warning summary shows **in [warn] log level** even with binary compatible conflicts.

## Detail

Eviction warning summary is:

```
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
```

[This is introduced in sbt 1.2.0](https://developer.lightbend.com/blog/2018-07-02-sbt-1-2-0/index.html):

> Displays only the eviction warning summary by default, and make it configurable using ThisBuild / evictionWarningOptions. lm211 and #3947 by @exoego

### My test

I tested **update** and **evicted** command in sbt 1.1.6 and 1.2.8.

source code to reproduce: https://github.com/bigwheel/sbt-warn-eviction-summary-inconsistency-behavior

Result:

| | [1.1.6 with b-compatible](https://github.com/bigwheel/sbt-warn-eviction-summary-inconsistency-behavior/blob/master/colorless-output.txt#L2-L18) | [1.1.6 with b-incompatible](https://github.com/bigwheel/sbt-warn-eviction-summary-inconsistency-behavior/blob/master/colorless-output.txt#L21-L45) | [1.2.8 with b-compatible](https://github.com/bigwheel/sbt-warn-eviction-summary-inconsistency-behavior/blob/master/colorless-output.txt#L48-L69) | [1.2.8 with b-incompatible](https://github.com/bigwheel/sbt-warn-eviction-summary-inconsistency-behavior/blob/master/colorless-output.txt#L72-L92) |
|--|--|--|--|--|
| Eviction warning summary<br>shows in update command | no | no | **yes** | yes |
| Log level of evicted command | info | warn | info | warn |

### Problem

I understand *evicted* command prints binary compatible conflict as [info] level and binary **in**compatible conflict as [warn] because binary compatible conflict is no problem in many case.
However, if there are only binary compatible conflicts Eviction warning summary shows **in [warn] level** in contrast to *evicted* command prints only **in [info] level**.

## Solution

I figured out some solutions.

### 1. Eviction warning sumary shows only there are binary **in**compatible conflicts

https://github.com/sbt/librarymanagement/blob/96a3293c/core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala#L317

```scala
if ((a.options.warnEvictionSummary || a.reportedEvictions.nonEmpty) && a.allEvictions.nonEmpty) {
```

to

```scala
if (a.options.warnEvictionSummary && a.reportedEvictions.nonEmpty) {
```

I think this is best fix.

### 2. Eviction warning sumary with info level

This is not easy fix because it seems like [we cannot select log level in there](https://github.com/sbt/librarymanagement/blob/96a3293c/core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala#L318).

### 3. Change default EvictionWarningOptions from summary to empty

[Easy fix](https://github.com/sbt/librarymanagement/blob/96a3293c/core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala#L73).

## Conclusion

Please tell me how to fix this.
After that, I will create Pull Request for it.

## Related to

[scala \- addSbtPlugin\(\.\.\.\) cause eviction warning but 'evicted' command shows nothing \- Stack Overflow](https://stackoverflow.com/questions/54049146/addsbtplugin-cause-eviction-warning-but-evicted-command-shows-nothing/54053209?noredirect=1#comment95028817_54053209)

### PR DESCRIPTION
**Pull request by bigwheel**
Fix #287.

All tests(113) passed in my local PC.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/288/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

File: core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala [hunk 1]
```diff
@@ -195,7 +195,8 @@ final class EvictionWarning private[sbt] (
     val scalaEvictions: Seq[EvictionPair],
     val directEvictions: Seq[EvictionPair],
     val transitiveEvictions: Seq[EvictionPair],
-    val allEvictions: Seq[EvictionPair]
+    val allEvictions: Seq[EvictionPair],
+    val binaryIncompatibleEvictionExists: Boolean
```
Comment (bigwheel) [inline core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala:199]: Oh, this line breaks binary compatibility....
I'm thinking how to fix #287 without binaryIncompatibleEvictionExists field now.

Comment (eed3si9n) [reply core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala:199]: Maybe you can change `final` to `sealed` and make a subclass of EvictionWarning like `private[sbt] final class EvictionWarningImpl` and cast into it later.

**Review by eed3si9n — APPROVED** [review]
