### PR TITLE
Fix the contains issue

### LINKED ISSUE #259: "Comparing unrelated types: String and ConfigRef" in CachedResolutionResolveEngine.scala
https://github.com/sbt/librarymanagement/blob/3fcc9e3629a329ed554e43d93a86de5ba3ad0242/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala#L971

screen shot 2018-08-02 at 0 42 21

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #259
Ref https://github.com/sbt/sbt/issues/3761

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/268/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

File: ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala [hunk 1]
```diff
@@ -967,8 +967,8 @@ private[sbt] trait CachedResolutionResolveEngine extends ResolveEngine {
       }
     log.debug(s"::: remapped configs $remappedConfigs")
     val configurations = rootModuleConfs map { conf0 =>
-      val remappedCRs = configurations0 filter { cr =>
-        remappedConfigs(conf0.getName) contains cr.configuration
+      val remappedCRs: Vector[ConfigurationReport] = configurations0 filter { cr =>
+        remappedConfigs(conf0.getName).contains[String](cr.configuration.name)
```
Comment (eed3si9n) [inline ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala:971]: This is the fix.
