### PR TITLE
move CrossVersion to src/

### LINKED ISSUE #4595: update task is not caching correctly
## steps

in sbt/sbt:

```
mainProj/compile
```

## problem

You see eviction warning, which is a sign that update task is running unnecessarily.

## expectation

update is cached.

## notes

Due to error-swallowing behavior of the cache, bugs are treated as cache miss.

Here's what happens if we let it throw exceptions instead:

```
sbt:sbtRoot> mainProj/compile
[error] jawn.IncompleteParseException: exhausted input
[error] 	at jawn.Parser.parse(Parser.scala:362)
[error] 	at jawn.SyncParser.parse(SyncParser.scala:24)
[error] 	at jawn.SupportParser.parseUnsafe(SupportParser.scala:12)
[error] 	at jawn.SupportParser.parseUnsafe$(SupportParser.scala:11)
[error] 	at sjsonnew.support.scalajson.unsafe.Parser$.parseUnsafe(Parser.scala:8)
[error] 	at sbt.internal.BuildStreams$.$anonfun$mkStreams$3(BuildStructure.scala:273)
[error] 	at sjsonnew.IsoString$$anon$1.from(IsoString.scala:27)
[error] 	at sbt.util.PlainInput.read(Input.scala:31)
[error] 	at sbt.util.FileBasedStore.$anonfun$read$1(CacheStore.scala:69)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.util.FileBasedStore.read(CacheStore.scala:69)
[error] 	at sbt.util.Tracked$CacheHelp.$anonfun$changed$1(Tracked.scala:186)
[error] 	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.util.Tracked$CacheHelp.changed(Tracked.scala:186)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:148)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:124)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2701)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled$)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.write(FlatUnionFormats.scala:220)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.addField(FlatUnionFormats.scala:208)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:46)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:9)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.addField(ModuleIDFormats.scala:9)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleDescriptorConfigurationFormats$$anon$1.write(ModuleDescriptorConfigurationFormats.scala:35)
[error] 	at sbt.librarymanagement.ModuleDescriptorConfigurationFormats$$anon$1.write(ModuleDescriptorConfigurationFormats.scala:9)
[error] 	at sjsonnew.FlatUnionFormats$$anon$3.write(FlatUnionFormats.scala:148)
[error] 	at sjsonnew.TupleFormats$$anon$3.write(TupleFormats.scala:72)
[error] 	at sjsonnew.TupleFormats$$anon$3.write(TupleFormats.scala:67)
[error] 	at sjsonnew.ImplicitHashWriters$$anon$1.write(ImplicitHashWriters.scala:22)
[error] 	at sjsonnew.SupportHasher.hashUnsafe(SupportHasher.scala:22)
[error] 	at sjsonnew.SupportHasher.hashUnsafe$(SupportHasher.scala:19)
[error] 	at sjsonnew.support.murmurhash.Hasher$.hashUnsafe(Hasher.scala:25)
[error] 	at sjsonnew.SupportHasher.$anonfun$hash$1(SupportHasher.scala:13)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sjsonnew.SupportHasher.hash(SupportHasher.scala:13)
[error] 	at sjsonnew.SupportHasher.hash$(SupportHasher.scala:12)
[error] 	at sjsonnew.support.murmurhash.Hasher$.hash(Hasher.scala:25)
[error] 	at sbt.util.Tracked$CacheHelp.changed(Tracked.scala:188)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:148)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:124)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2701)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (testAgentProj / update) jawn.IncompleteParseException: exhausted input
[error] (ProjectRef(uri("file:/Users/eed3si9n/work/sbt-modules/util/"), "utilInterface") / update) scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled$)
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes sbt/sbt#4595
Ref #290
Ref #280

This is bit of an odd one.

To keep bincompat and also to fix sbt 0.13 compatibility issue we have made `Disabled` companion object extend `Disabled` type.
This actually created a subtle deserialization issue:

```
[error] scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled$)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.write(FlatUnionFormats.scala:220)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.addField(FlatUnionFormats.scala:208)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:46)
```

This is because Contraband generates `flatUnionFormat5[CrossVersion, Disabled, ...]` for all of the subtypes of `CrossVersion`, which uses the runtime type information. Now that `Disabled` object is also in the mix, this created JSON that `CrossVersionFormats` cannot deserialize. This brings the code into src/ so we can write this part manually.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/296/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

File: core/src/main/scala/sbt/librarymanagement/CrossVersion.scala [hunk 1]
```diff
@@ -0,0 +1,330 @@
...
+
+trait CrossVersionFormats {
+  self: sjsonnew.BasicJsonProtocol
+    with sbt.librarymanagement.DisabledFormats
+    with sbt.librarymanagement.BinaryFormats
+    with sbt.librarymanagement.ConstantFormats
+    with sbt.librarymanagement.PatchFormats
+    with sbt.librarymanagement.FullFormats =>
+  implicit lazy val CrossVersionFormat: JsonFormat[sbt.librarymanagement.CrossVersion] =
+    flatUnionFormat6[sbt.librarymanagement.CrossVersion,
```
Comment (eed3si9n) [inline core/src/main/scala/sbt/librarymanagement/CrossVersion.scala:323]: The only change in this PR is here.
